[project]
name = "bedrock-workshop"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "boto3==1.37.25",
    "chromadb==0.6.3",
    "click==8.1.8",
    "prompt-toolkit==3.0.50",
    "rich==13.7.0",
]
